"""player stats columns

Revision ID: 209171472d94
Revises: d1e2f3a4b5c6
Create Date: 2026-01-07 22:25:11.692610

"""
from alembic import op
import sqlalchemy as sa


revision = '209171472d94'
down_revision = 'd1e2f3a4b5c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
